### ISSUE TITLE
Import not working properly

### ISSUE THREAD

**Issue by JosephFidelino** [CradlePHP/Cradle#44]
Data is not updating after importing. Also, the user receives 500 internal server error upon uploading the import file.

<img width="1277" alt="screen shot 2018-04-11 at 8 02 59 am" src="https://user-images.githubusercontent.com/26085313/38593440-eaeebf44-3d73-11e8-8ab4-d788ba9c266a.png">

**Comment by cjzamora** [comment]
For Reference:  https://github.com/CradlePHP/cradle-system/commit/ee4d4246659418d8c9a5bc26b007a37612ad728c and https://github.com/CradlePHP/Cradle/commit/ac82ad54e766d59feab58d15477870669b8a4604

Instead of sending the csv data via using the regular post data, i encoded the entire data as a json string then parse that json string from request body to avoid max variable limit error.

**Comment by JosephFidelino** [comment]
Tested on Local. Works fine on my end. Tried to upload 5000 rows of data. Good to close.

![screen shot 2018-04-18 at 6 10 09 pm](https://user-images.githubusercontent.com/26085313/38926190-6fa32fc0-4334-11e8-9e0d-5c3f0bcad15b.png)
![screen shot 2018-04-18 at 6 10 34 pm](https://user-images.githubusercontent.com/26085313/38926191-6fdbba66-4334-11e8-99cf-63a627bfdb6a.png)
![screen shot 2018-04-18 at 6 11 26 pm](https://user-images.githubusercontent.com/26085313/38926192-70114226-4334-11e8-9db3-6fbe51c80779.png)
